#American News Generator by Dc117 Corp.
#Controls:
#Enter: New Sentance

print('American News Generator V3.10')
name=['Neha', 'SirWojt', 'An SCR Nerd', 'Lee', 'Sam', 'DormentCoder', 'theexistman', 'Max', 'Ethen', 'Thondori', 'Jeremy Clarkson', 'Kermit the Frog', 'Kyes Sister', 'Currys PC World', 'Rourke', 'Solid Snake', 'Raiden', 'Kingpin', 'Florida Man', 'Kim Yo-jong', 'Calebs Sister', 'Gordon Ramsey', 'Texan Mother', 'Calebs Cousin', 'Calefornia Woman', 'Michael Jackson', 'Colonel Sanders', 'Ronald McDonald', 'Donald Trump', 'Boris Johnson', 'The Queen', 'Jacob Rees Mogg', 'Alan Carr', 'Putin', 'Kim Jong Un', 'Harvey', 'Dylan', 'Caleb', 'Harry', 'Leo', 'Ben', 'Bob', 'Ella', 'Grace', 'Fabian', 'CallMeCarson', 'SniperWolf', 'GeorgeNotFound', 'Dream', 'Slimesical', 'TommyInnit', 'KSI', 'Technoblade', 'Kye', 'Roy Liechtenstein', 'George', 'Kornel', 'Billy']
adverb=['abnormally', 'unbearably', 'dreamily', 'excessively', 'casually', 'hopelessly', 'honestly', 'quickly', 'said, "Big issue", to', 'slowly', 'weirdly', 'forcefully', 'constantly', 'throughly', 'secretly', 'accidently', 'calmly', 'jealously', 'generously', 'furiously', 'naturally', 'gladly', 'suspiciously', 'violently', 'messily', 'wishfully', 'eagerly', 'specifically', 'mysteriously', 'happily', 'sadly', 'cautiously', 'doubtfully', 'obidiently']
verb=['buys', 'rides', 'kicks', 'developed', 'turned into', 'evolved into', 'ro-raced', 'chose to become', 'got possessed by', 'made it rain because of', 'flexed their muscles to', 'said, "Take a good look at yourselfs in the mirror", to', 'did the renegade alongside', 'pulled out on', 'licked', 'escaped from', 'got a hit on by', 'got shanked by', 'bombed', 'crashed into', 'kidnapped', 'was placed under suspicion by', 'was arrested by', 'squealed at', 'payed rent towards', 'devolved into becoming', 'examined', 'evaded', 'enjoyed being in the company of', 'whispered to', 'finished off', 'tortured', 'strangled', 'erased out of existance', 'cured', 'punched', 'killed', 'played with', 'smacked', 'drowns', 'injected bleach into', 'shot', 'got killed by', 'ate', 'killed themselfs over', 'sussy vent killed', 'beat the living shit out of', 'pissed themselfs because of them being scared of', 'destroyed', 'earned the right to possess', 'joined alongside', 'offered a very nice deal to', 'accepted an offer from', 'got melted by', 'behaved well to honor', 'protected', 'built a statue of', 'wrapped themselfs around', 'identified as', 'asked to go out on a date with', 'compared themselfs with', 'relaxed with', 'trusted', 'wanted to go out with', 'got hunted down by', 'spilled OJ on', 'walked up to', 'grabbed', 'laughed at', 'soothed', 'escaped from', 'programmed how to auto generate']
noun=['A Dreamcast Console', 'a lion', 'a bicycle', 'a plane', 'a horse', 'Lillemala', 'Elmo', 'an air-con unit', 'Lebron James', 'a VRC e-girl', 'a priest', 'an exorcist', 'a potato', 'an orange', 'an eggplant', 'a big pair of peaches', 'James May', 'a bottle of lotion with some tissues', 'a porta-potty', 'an emo', 'a muslim', 'a terrorist', 'a cow', 'Walmart', 'a pig', 'a pigeon', 'a deer', 'a drone', 'a goat', 'a guinea pig', 'a rat', 'a tentacle monster', 'Big Boss', 'a Starbucks delivery', 'Mckenzies Meats', 'a McDonalds drive-thru', 'a Subways drive-thru', 'an Indian man on a moped', 'Tobys Carvery', 'Sainsburys', 'a Tescos Clubcard', 'Cex Trades', 'some flex tape', 'Spiderman', 'a Windows XP computer', 'Senetor Armstrong', 'Liquid Ocelot', 'a Tik Tok dancer', 'a pair of HUGE honka donka mommy milkers', 'a box of burger king foot lettuce', 'a Worksop chav', 'an asian girl', 'Kyes sister', 'an instagram model', 'a super model', 'their sister', 'a big bottle of lube', 'Calebs Sister', 'their asshole', 'their siblings', 'Ronald McDonald', 'a catboy', 'a car', 'McDonalds', 'Kim Jong Ill', 'their cousin', 'a rotten orange', 'Colonel Sanders', 'a Chicken Legend', 'a Realistic Minecraft Steve', 'a Very Annoying Orange', 'a tower', 'an ATV', 'a tank', 'a triangle', 'a tree', 'a sandwich', 'a sausage', 'a piano', 'a youtuber', 'an orphan', 'a bacon baguette', 'a squeaky shoe', 'a toe', 'a Female',]
postnoun=['whilst playing outro music, "Out, peace", said the individual', '"Lmao, L moment", was what they said', 'while packing an entire Greggs', 'While screaming, "HAMMON!!!"', 'due to a skill issue, "Get good bru" said the individual', 'due to them contracting Stage 3 Cancer', 'due to them contracting HIV', 'while shouting, "Nanomachines son! They activate towards physical trauma!!!"', 'while saying to them, "Buisness is booming!"', 'while screaming, "Ah shit, here we go again..."', 'while screaming, "LEEEEEEEEEEEEEROYYYYYYYYYYY JENKIIIIIINS!!!!!!"', 'while moonwalking off into the distance', 'while screaming, "Why is it so SMALL?!?!!"', 'while impersonating Gordon Ramsey', 'while screaming, "ITS FUCKING RAAAW!!!"', 'while wearing a wedding dress', 'while wearing a bright pink latex dress', 'infront of their wife', 'it was a slippery escape', 'while wearing nothing but one sole shoe and one lonely glove', 'while wearing nothing but a headband', 'while screaming "COLONEL, IM NAKED!!!"', 'while screaming profanitys', 'while beating them with a newspaper', 'in todays top story', 'while eating a cat', 'while sweating profusely', 'while beating them with a dildo']
connectives=['and then', 'therefor', 'because of', 'due to', 'consequently', 'besides that travisty', 'as a result', 'but sometimes', 'this has caused', 'this results in', 'however', 'even though', 'suddently', 'until', 'furthermore', 'then all of a sudden', 'despite that', 'but nevertheless', 'yet alternatively', 'meanwhile', 'as well as', 'then immediately']
news_starter= ['This is the News at 10 with Hugh Edwards,', 'Urhhhh guys, look at this.', 'Hello everyone and welcome to daily AiGP Update!', 'Something bad has just happened! Worse then your parents divorce!!!', 'This is a BBC special news report,', 'No.13', 'No.7', 'No.12', 'No.15', 'No.17', 'OH FUCK ME! LOOK AT THIS!!!', 'This just in,', 'Todays top story:', 'A tragedy has emurged:', 'Todays headliner is,', 'Todays recent scandles are:', 'This is unbeliveable!!', 'Have a good look at this!', 'Have a long hard read of this! You wont believe your eyes!!']
from random import randint
def pick(words):
    num_words=len(words)
    num_picked=randint(0, num_words-1)
    word_picked=words[num_picked]
    return word_picked
while True:
    print(pick(news_starter), pick(name), pick(adverb), pick(verb), pick(noun), pick(postnoun),  pick(connectives), ',', pick(name), pick(adverb), pick(verb), pick(noun), pick(postnoun), end='.')
    input()